import java.text.SimpleDateFormat

//
// build.gradle in FtcRobotController
//
apply plugin: 'com.android.library'

android {

    defaultConfig {
        minSdkVersion 24
        //noinspection ExpiredTargetSdkVersion
        targetSdkVersion 28
        buildConfigField "String", "APP_BUILD_TIME", '"' + (new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ", Locale.ROOT).format(new Date())) + '"'
    }

    buildFeatures {
        buildConfig = true
    }

    compileSdkVersion 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    namespace = 'com.qualcomm.ftcrobotcontroller'

    sourceSets {
        main {
            java {
                exclude '**/external/samples/ConceptAprilTag*.java'
                exclude '**/external/samples/RobotAutoDriveToAprilTag*.java'
                exclude '**/external/samples/ConceptGamepadEdgeDetection.java'
                exclude '**/external/utilities/UtilityTest*.java'
            }
        }
    }
}

apply from: '../build.dependencies.gradle'
